'use strict';

// Vexel code generation — Vexel AST -> Rust source -> rustc -> native exe.
// All values use VexVal (tagged union) with static type checking done
// earlier. Globals live in a thread-local map; functions are native
// Rust fns returning Result. This is genuine native compilation via
// the Rust backend, not an interpreter.

const fs = require('fs');
const path = require('path');

function loadRuntime() {
  // __dirname = vexel/compiler/codegen ; runtime at vexel/runtime (two levels up)
  const candidates = [
    path.join(__dirname, '..', '..', 'runtime', 'vex_runtime.rs'),
    path.join(process.cwd(), 'vexel', 'runtime', 'vex_runtime.rs'),
    path.join(process.cwd(), 'runtime', 'vex_runtime.rs'),
  ];
  let lastErr = null;
  for (const p of candidates) {
    try {
      let src = fs.readFileSync(p, 'utf8');
      // Vexel 3.4 Atlas lives in its own subsystem file, concatenated
      // here so generated programs stay single-file for rustc.
      try {
        src += '\n' + fs.readFileSync(path.join(path.dirname(p), 'atlas.rs'), 'utf8');
      } catch (e) { /* atlas.rs rides along when present */ }
      // Atlas v0.4 GPU device layer (lazy loader; inert without a backend).
      try {
        src += '\n' + fs.readFileSync(path.join(path.dirname(p), 'atlas_gpu.rs'), 'utf8');
      } catch (e) { /* atlas_gpu.rs rides along when present */ }
      // Atlas v0.5 model layer: always included so `any`-based model
      // member/forward calls resolve at runtime (single-module hygiene;
      // rustc has no -D warnings, so unused fns cost nothing).
      for (const rf of ['atlas_format.rs', 'atlas_hf.rs', 'atlas_safetensors.rs', 'atlas_model.rs']) {
        try {
          src += '\n' + fs.readFileSync(path.join(path.dirname(p), rf), 'utf8');
        } catch (e) { /* model runtime rides along when present */ }
      }
      return src;
    } catch (e) {
      lastErr = e;
    }
  }
  throw lastErr;
}

function sanitizeIdent(s) {
  return String(s).replace(/[^A-Za-z0-9_]/g, '_');
}

function rustEscape(s) {
  return String(s)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

function buildPrefixes(order) {
  const map = new Map(); // absPath -> prefix
  order.forEach((absPath, idx) => {
    const base = path.basename(absPath, path.extname(absPath));
    const prefix = `m${idx}_${sanitizeIdent(base)}`;
    map.set(path.normalize(absPath), prefix);
  });
  return map;
}

function generate(loadResult, analyzeResult) {
  const { modules, order } = loadResult;
  const { scopes } = analyzeResult;
  const runtime = loadRuntime();
  const prefixMap = buildPrefixes(order);
  const norm = (p) => path.normalize(p);
  const prefixOf = (absPath) => prefixMap.get(norm(absPath));

  const out = [];
  out.push('// Generated by Vexel v0.1 compiler (Vexel -> Rust -> native). Do not edit.');
  out.push(runtime);
  out.push('');

  // Forward declarations not needed in Rust (items order-independent except statics).
  // Emit functions for each module in order.
  for (const absPath of order) {
    const prefix = prefixOf(absPath);
    const scope = scopes.get(norm(absPath));
    const mod = modules.get(norm(absPath));
    out.push(`// ===== Module ${mod.file} (${prefix}) =====`);
    // Functions
    for (const [, fn] of scope.functions) {
      out.push(genFunction(prefix, fn, scope, scopes, prefixMap, modules));
      out.push('');
    }
  }

  // Init guards + init fns
  for (const absPath of order) {
    const prefix = prefixOf(absPath);
    const scope = scopes.get(norm(absPath));
    const mod = modules.get(norm(absPath));
    const guard = `${prefix.toUpperCase()}__INIT`;
    out.push(`static ${guard}: AtomicBool = AtomicBool::new(false);`);
    out.push(`fn ${prefix}__init() -> Result<(), String> {`);
    out.push(`    if ${guard}.swap(true, Ordering::SeqCst) { return Ok(()); }`);
    const ctx = {
      prefixMap,
      currentPrefix: prefix,
      currentScope: scope,
      scopes,
      modules,
      inFunction: false,
      locals: new Set(),
      inTryClosure: false,
      inCatch: false,
      indent: '    ',
    };
    for (const st of mod.ast.body) {
      // Skip declarations handled elsewhere: imports, structs, funcs.
      // (Unused component/theme declarations emit nothing in console programs.)
      // Imports' init is called from vex_main in order; no per-import code here.
      // But need to keep execution order? Top-level code executes after deps' init
      // (since vex_main calls deps first). Within a module, top-level stmts run in order.
      if (st.type === 'ImportDecl' || st.type === 'StructDecl' || st.type === 'EnumDecl' || st.type === 'TestBlock' || st.type === 'FuncDecl' || st.type === 'ComponentDecl' || st.type === 'ThemeDecl' || st.type === 'StyleDecl') continue;
      if (st.type === 'PublicDecl') {
        const inner = st.decl;
        if (!inner) continue;
        if (inner.type === 'FuncDecl' || inner.type === 'StructDecl' || inner.type === 'EnumDecl') continue;
        // public var assign: emit
        out.push(genStatement(inner, ctx, '    '));
        continue;
      }
      out.push(genStatement(st, ctx, '    '));
    }
    out.push('    Ok(())');
    out.push('}');
    out.push('');
  }

  // Main entry: call inits in topo order (deps first, entry last)
  out.push('fn vex_main() -> Result<(), String> {');
  for (const absPath of order) {
    const prefix = prefixOf(absPath);
    out.push(`    ${prefix}__init()?;`);
  }
  out.push('    Ok(())');
  out.push('}');
  out.push('');
  out.push('fn main() {');
  out.push('    if let Err(e) = vex_main() {');
  out.push('        eprintln!("{}", e);');
  out.push('        std::process::exit(1);');
  out.push('    }');
  out.push('}');
  out.push('');

  return out.join('\n');
}

function genFunction(prefix, fn, scope, scopes, prefixMap, modules) {
  const fname = `${prefix}__${sanitizeIdent(fn.name)}`;
  const params = fn.params.map((p) => `v_${sanitizeIdent(p)}: VexVal`).join(', ');
  const lines = [];
  lines.push(`fn ${fname}(${params}) -> Result<VexVal, String> {`);
  const ctx = {
    prefixMap,
    currentPrefix: prefix,
    currentScope: scope,
    scopes,
    modules,
    inFunction: true,
    locals: new Set(fn.params.map((p) => p)),
    inTryClosure: false,
    inCatch: false,
  };
  // Vexel has function scope (no block scope), but Rust braces DO scope
  // `let` bindings. A name first assigned inside an if/loop/try branch was
  // invisible outside it (rustc E0425). Hoist every assigned local to the
  // top of the function, initialized to Null. Programs that compiled before
  // are unaffected (same variable, wider-but-equivalent scope).
  for (const n of collectRustLocals(fn.body)) {
    if (ctx.locals.has(n)) continue;
    ctx.locals.add(n);
    lines.push(`    let mut v_${sanitizeIdent(n)}: VexVal = VexVal::Null;`);
  }
  if (fn.body.length === 0) {
    lines.push('    Ok(VexVal::Null)');
  } else {
    for (const st of fn.body) {
      lines.push(genStatement(st, ctx, '    '));
    }
    lines.push('    Ok(VexVal::Null)');
  }
  lines.push('}');
  return lines.join('\n');
}

function globalKey(prefix, name) {
  return `${prefix}__${name}`;
}

// Every name assigned anywhere in a function body (any nesting depth) is a
// function-scoped local in Vexel. Mirrors genVarAssign/SetOutputStmt: VarRef
// targets (except the `output` buffer) and SetOutputStmt dests.
function collectRustLocals(stmts) {
  const names = new Set();
  const walk = (list) => {
    for (const st of list || []) {
      if (!st || typeof st !== 'object') continue;
      if (st.type === 'VarAssign' && st.target && st.target.type === 'VarRef' && st.target.name !== 'output') {
        names.add(st.target.name);
      } else if (st.type === 'SetOutputStmt' && st.dest !== 'output') {
        names.add(st.dest);
      } else if (st.type === 'IfStmt') {
        for (const br of st.branches || []) walk(br.body);
        walk(st.elseBody);
      } else if (st.type === 'TryStmt') {
        walk(st.tryBody);
        walk(st.catchBody);
      } else if (st.type === 'RepeatCount' || st.type === 'RepeatTill') {
        walk(st.body);
      } else if (st.type === 'MatchStmt') {
        for (const arm of st.arms || []) walk(arm.body);
      } else if (st.type === 'InferenceStmt') {
        walk(st.body);
      }
    }
  };
  walk(stmts);
  return names;
}

function resolveModulePrefix(ctx, moduleName) {
  const imp = ctx.currentScope.imports.find((im) => im.moduleName === moduleName);
  if (!imp) return null;
  return ctx.prefixMap.get(path.normalize(imp.absPath));
}

const UI_NODE_TYPES = new Set([
  'CreateWindow', 'CreateContainer', 'AddWidget', 'AddToContainer', 'ComponentUse',
  'UISetProp', 'UISetMinMax', 'UISetPosition', 'UICenter', 'UIUseTheme',
  'UIShowDialog', 'UIAnimate', 'UIEventHandler',
  'UIAddNode', 'UIEventRef', 'AskExpr', 'ChooseFile', 'ChooseColor', 'ChooseFolder',
  'TimerStmt', 'RemoveStmt', 'CopyStmt', 'StyleDecl', 'PercentOf',
  'ShowNotification',
]);

function atlasLocArgs(ctx) {
  const l = ctx.loc || { file: 'main.vxl', line: 1, column: 1 };
  return `"${rustEscape(l.file)}", ${l.line}u32, ${l.column}u32`;
}

// Vexel 3.4 Atlas: build the nested VexVal list that backs tensor
// data and shapes (literals inline, anything else via genExpr).
function genTensorDataList(elements, ctx) {
  const parts = elements.map((e) => {
    if (e.type === 'ListLit') return genTensorDataList(e.elements, ctx);
    if (e.type === 'IntLit') return `VexVal::Int(${e.value}i64)`;
    if (e.type === 'FloatLit') return `VexVal::Float((${e.value}) as f64)`;
    return `(${genExpr(e, ctx)})`;
  });
  return `VexVal::List(Rc::new(RefCell::new(vec![${parts.join(', ')}])))`;
}

function genStatement(st, ctx, indent) {
  if (UI_NODE_TYPES.has(st.type)) {
    throw new Error('INTERNAL: UI syntax reached the console backend (needs a window; use the UI backend).');
  }
  // Vexel 3.4 Atlas: every statement refreshes the source location so
  // tensor errors can name file/line/column. One call per statement.
  if (st && st.token) {
    ctx.loc = {
      file: path.basename((ctx.currentScope && ctx.currentScope.file) || 'main.vxl'),
      line: st.token.line || 1,
      column: st.token.column || 1,
    };
  }
  return `${indent}vex_atlas_loc(${atlasLocArgs(ctx)});\n` + genStatementInner(st, ctx, indent);
}

function genStatementInner(st, ctx, indent) {
  switch (st.type) {
    case 'VarAssign':
      return genVarAssign(st, ctx, indent);
    case 'PrintStmt':
      if (st.isFile) {
        return `${indent}vex_print_file("${rustEscape(st.filePath)}")?;`;
      }
      return `${indent}vex_print(&(${genExpr(st.arg, ctx)}));`;
    case 'IfStmt': {
      let s = '';
      st.branches.forEach((br, idx) => {
        const cond = genExpr(br.cond, ctx);
        const kw = idx === 0 ? 'if' : 'else if';
        s += `${indent}${kw} ((${cond})).as_bool()? {\n`;
        for (const inner of br.body) {
          s += genStatement(inner, ctx, indent + '    ') + '\n';
        }
        s += `${indent}}`;
      });
      if (st.elseBody) {
        s += ` else {\n`;
        for (const inner of st.elseBody) {
          s += genStatement(inner, ctx, indent + '    ') + '\n';
        }
        s += `${indent}}`;
      }
      return s;
    }
    case 'RepeatCount': {
      const cnt = genExpr(st.count, ctx);
      let s = '';
      s += `${indent}{\n`;
      s += `${indent}    let __vex_cnt = ((${cnt})).as_int()?;\n`;
      s += `${indent}    if __vex_cnt < 0 { return Err(String::from("Repeat count must be non-negative.")); }\n`;
      s += `${indent}    for __vex_i in 0..__vex_cnt {\n`;
      // Vexel 2.9: cooperative cancellation checkpoints inside tasks.
      if (ctx.inTask) s += `${indent}        vex_task_check_cancel()?;\n`;
      for (const inner of st.body) {
        s += genStatement(inner, ctx, indent + '        ') + '\n';
      }
      s += `${indent}    }\n`;
      s += `${indent}}`;
      return s;
    }
    case 'RepeatTill': {
      const cond = genExpr(st.cond, ctx);
      let s = '';
      s += `${indent}while !((${cond})).as_bool()? {\n`;
      // Vexel 2.9: cooperative cancellation checkpoints inside tasks.
      if (ctx.inTask) s += `${indent}    vex_task_check_cancel()?;\n`;
      for (const inner of st.body) {
        s += genStatement(inner, ctx, indent + '    ') + '\n';
      }
      s += `${indent}}`;
      return s;
    }
    case 'TaskStmt': {
      // Vexel 2.9 console tasks: snapshot globals, run the body on a
      // worker thread, bind the numeric handle. Reads fall back to the
      // worker's seeded globals; writes stay worker-local; `result`
      // returns through the locked handoff.
      const key = globalKey(ctx.currentPrefix, st.name);
      let s = `${indent}{\n`;
      s += `${indent}    let __vex_snap = vex_snapshot_globals();\n`;
      s += `${indent}    let __vex_id = vex_task_spawn(__vex_snap, Box::new(move || {\n`;
      s += `${indent}        let mut v_result: VexVal = VexVal::Null;\n`;
      const bodyCtx = Object.assign({}, ctx, { inTask: true });
      if (!bodyCtx.locals) bodyCtx.locals = new Set();
      bodyCtx.locals.add('result');
      for (const n of collectRustLocals(st.body)) {
        if (n === 'result' || bodyCtx.locals.has(n)) continue;
        bodyCtx.locals.add(n);
        s += `${indent}        let mut v_${sanitizeIdent(n)}: VexVal = VexVal::Null;\n`;
      }
      // NOTE: inTask bodies use function-style locals; reads resolve to
      // worker-seeded globals via the normal fallback. result is local.
      const fnCtx = Object.assign({}, bodyCtx, { inFunction: true });
      for (const inner of st.body) {
        s += genStatement(inner, fnCtx, indent + '        ') + '\n';
      }
      s += `${indent}        vex_json_stringify(&v_result)\n`;
      s += `${indent}    }));\n`;
      s += `${indent}    vex_set("${rustEscape(key)}", VexVal::Int(__vex_id as i64));\n`;
      s += `${indent}}`;
      return s;
    }
    case 'WaitTaskStmt': {
      // Vexel 2.9: block until the task reaches a terminal state.
      const h = genExpr(st.handle, ctx);
      return `${indent}vex_task_wait(&(${h}))?;`;
    }
    case 'HttpTimeoutStmt': {
      const v = genExpr(st.secs, ctx);
      return `${indent}vex_http_set_timeout(&(${v}))?;`;
    }
    case 'ReturnStmt': {
      if (!ctx.inFunction) {
        return `${indent}return Err(String::from("Return outside function."));`;
      }
      if (ctx.inTryClosure) {
        if (st.value) {
          return `${indent}return Ok(Some((${genExpr(st.value, ctx)})));`;
        }
        return `${indent}return Ok(Some(VexVal::Null));`;
      }
      if (st.value) {
        return `${indent}return Ok((${genExpr(st.value, ctx)}));`;
      }
      return `${indent}return Ok(VexVal::Null);`;
    }
    case 'RaiseStmt': {
      const v = genExpr(st.value, ctx);
      return `${indent}return Err(((${v})).to_display());`;
    }
    case 'InputStmt': {
      const p = genExpr(st.prompt, ctx);
      return `${indent}vex_set_output(vex_input(&(((${p})).to_display())));`;
    }
    case 'SetOutputStmt': {
      if (ctx.inFunction) {
        if (ctx.locals.has(st.dest)) {
          return `${indent}v_${sanitizeIdent(st.dest)} = vex_get_output();`;
        }
        ctx.locals.add(st.dest);
        return `${indent}let mut v_${sanitizeIdent(st.dest)} = vex_get_output();`;
      }
      const key = globalKey(ctx.currentPrefix, st.dest);
      return `${indent}vex_set("${rustEscape(key)}", vex_get_output());`;
    }
    case 'MakeStmt': {
      // Vexel 3.5 Atlas: require-gradients flips a shared flag in
      // place (no rebinding — every handle sees the same tensor).
      if (st.mode === 'require-gradients') {
        if (ctx.inFunction && ctx.locals.has(st.target)) {
          return `${indent}vex_tensor_require_grad(&v_${sanitizeIdent(st.target)}.clone())?;`;
        }
        const key = globalKey(ctx.currentPrefix, st.target);
        return `${indent}vex_tensor_require_grad(&vex_get("${rustEscape(key)}"))?;`;
      }
      // Vexel 2.0: upper | lower | number | string | boolean.
      const mode = st.mode === 'upper' ? 'vex_make_upper'
        : st.mode === 'lower' ? 'vex_make_lower'
        : st.mode === 'number' ? 'vex_make_number'
        : st.mode === 'string' ? 'vex_make_string'
        : 'vex_make_boolean';
      if (ctx.inFunction && ctx.locals.has(st.target)) {
        return `${indent}v_${sanitizeIdent(st.target)} = ${mode}(&v_${sanitizeIdent(st.target)}.clone())?;`;
      }
      // Check if local? If in function but not yet local, could it be global?
      // `make` requires existing var; if in function and not local, assume global of current module.
      if (ctx.inFunction) {
        // Could be global — update global
        const key = globalKey(ctx.currentPrefix, st.target);
        return `${indent}vex_set("${rustEscape(key)}", ${mode}(&vex_get("${rustEscape(key)}"))?);`;
      }
      const key = globalKey(ctx.currentPrefix, st.target);
      return `${indent}vex_set("${rustEscape(key)}", ${mode}(&vex_get("${rustEscape(key)}"))?);`;
    }
    case 'WaitStmt': {
      // Vexel 2.0: wait 2 seconds (blocking sleep; fine in console too).
      // Vexel 2.9: inside tasks the sleep is cancellation-aware.
      const v = genExpr(st.value, ctx);
      if (ctx.inTask) {
        return `${indent}{\n` +
          `${indent}    let __vex_w = (${v});\n` +
          `${indent}    let __vex_secs: f64 = match &__vex_w { VexVal::Int(i) => *i as f64, VexVal::Float(f) => *f, _ => return Err("Wait needs a number of seconds.".to_string()) };\n` +
          `${indent}    vex_task_sleep(__vex_secs)?;\n` +
          `${indent}}`;
      }
      return `${indent}{\n` +
        `${indent}    let __vex_w = (${v});\n` +
        `${indent}    let __vex_secs: f64 = match &__vex_w { VexVal::Int(i) => *i as f64, VexVal::Float(f) => *f, _ => return Err("Wait needs a number of seconds.".to_string()) };\n` +
        `${indent}    if __vex_secs < 0.0 { return Err("Wait needs a non-negative number of seconds.".to_string()); }\n` +
        `${indent}    std::thread::sleep(std::time::Duration::from_secs_f64(__vex_secs));\n` +
        `${indent}}`;
    }
    case 'JsonWriteStmt': {
      // Vexel 2.0: json write data to "player.json".
      const v = genExpr(st.value, ctx);
      const p = genExpr(st.path, ctx);
      return `${indent}vex_json_write(&(${v}), &(((${p})).to_display()))?;`;
    }
    case 'TerminalStmt': {
      // Vexel 2.9: persistent shell session; cd/run only (parser-checked).
      let s = `${indent}{\n`;
      for (const inner of st.body) {
        s += genStatement(inner, ctx, indent + '    ') + '\n';
      }
      s += `${indent}}`;
      return s;
    }
    case 'CdStmt': {
      const d = genExpr(st.dir, ctx);
      return `${indent}vex_term_cd(&(${d}))?;`;
    }
    case 'RunStmt': {
      const c = genExpr(st.cmd, ctx);
      return `${indent}vex_term_run_print(&(${c}))?;`;
    }
    case 'FileWriteStmt': {
      const v = genExpr(st.value, ctx);
      const p = genExpr(st.path, ctx);
      return `${indent}vex_file_write(&(${v}), &(((${p})).to_display()))?;`;
    }
    case 'FileAppendStmt': {
      const v = genExpr(st.value, ctx);
      const p = genExpr(st.path, ctx);
      return `${indent}vex_file_append(&(${v}), &(((${p})).to_display()))?;`;
    }
    case 'FileDeleteStmt': {
      const p = genExpr(st.path, ctx);
      return `${indent}vex_file_delete(&(((${p})).to_display()))?;`;
    }
    case 'FileCopyStmt': {
      const f = genExpr(st.from, ctx);
      const t = genExpr(st.to, ctx);
      return `${indent}vex_file_copy(&(((${f})).to_display()), &(((${t})).to_display()))?;`;
    }
    case 'FileMoveStmt': {
      const f = genExpr(st.from, ctx);
      const t = genExpr(st.to, ctx);
      return `${indent}vex_file_move(&(((${f})).to_display()), &(((${t})).to_display()))?;`;
    }
    case 'DirCreateStmt': {
      const p = genExpr(st.path, ctx);
      return `${indent}vex_dir_create(&(((${p})).to_display()))?;`;
    }
    case 'DirDeleteStmt': {
      const p = genExpr(st.path, ctx);
      return `${indent}vex_dir_delete(&(((${p})).to_display()))?;`;
    }
    case 'DirCopyStmt': {
      const f = genExpr(st.from, ctx);
      const t = genExpr(st.to, ctx);
      return `${indent}vex_dir_copy(&(((${f})).to_display()), &(((${t})).to_display()))?;`;
    }
    case 'DirMoveStmt': {
      const f = genExpr(st.from, ctx);
      const t = genExpr(st.to, ctx);
      return `${indent}vex_dir_move(&(((${f})).to_display()), &(((${t})).to_display()))?;`;
    }
    case 'TryStmt': {
      return genTry(st, ctx, indent);
    }
    case 'AssertStmt': {
      // Vexel 2.9: runtime boolean check; failures name file and line.
      const c = genExpr(st.cond, ctx);
      const fname = rustEscape(path.basename((ctx.currentScope && ctx.currentScope.file) || 'main.vxl'));
      const line = (st.token && st.token.line) || 1;
      return `${indent}if !(((${c})).as_bool()?) { return Err("Assertion failed (${fname} line ${line}).".to_string()); }`;
    }
    case 'MatchStmt': {
      // Vexel 2.9: match desugars to an == chain (subject evaluated once).
      let s = `${indent}{\n`;
      s += `${indent}    let __vex_m = (${genExpr(st.subject, ctx)});\n`;
      st.arms.forEach((arm, idx) => {
        const p = arm.pattern;
        const kw = idx === 0 ? 'if' : 'else if';
        if (p.type === 'MatchDefault') {
          s += `${indent}${idx === 0 ? 'if true' : 'else'} {\n`;
        } else {
          let test = null;
          if (p.type === 'MatchLit') {
            if (p.litType === 'STRING') test = `VexVal::Str("${rustEscape(p.value)}".to_string())`;
            else if (p.litType === 'BOOL') test = `VexVal::Bool(${p.value ? 'true' : 'false'})`;
            else if (p.litType === 'DECIMAL') test = `VexVal::Float((${p.value}) as f64)`;
            else test = `VexVal::Int(${p.value}i64)`;
          } else if (p.type === 'MatchNull') {
            test = 'VexVal::Null';
          } else if (p.type === 'MatchEnum') {
            test = `VexVal::Str("${rustEscape(p.value)}".to_string())`;
          }
          s += `${indent}${kw} ((vex_eq(&__vex_m, &(${test}))?).as_bool()?) {\n`;
        }
        for (const inner of arm.body) {
          s += genStatement(inner, ctx, indent + '    ') + '\n';
        }
        s += `${indent}}`;
      });
      s += `\n${indent}}`;
      return s;
    }
    case 'MoveStmt': {
      // Vexel 3.6 Atlas: `move x to gpu|cpu` mutates the shared tensor in
      // place (aliases and gradients see the new device).
      const e = genExpr(st.expr, ctx);
      return `${indent}{ vex_move_device(&(${e}), "${st.device}")?; }`;
    }
    case 'SaveModelStmt': {
      // Atlas v0.5: `save model <m> to "<dir>"` — atomic folder write.
      const v = genExpr(st.value, ctx);
      const p = genExpr(st.path, ctx);
      return `${indent}{ vex_model_save(&(${v}), &(((${p})).to_display()))?; }`;
    }
    case 'InferenceStmt': {
      // Atlas v0.5: `with inference { ... }` — RAII guard suppresses
      // gradient tracking inside the block (underscore name: no warning).
      let s = `${indent}{\n${indent}    let _vex_inference_guard = vex_inference_guard();\n`;
      for (const inner of st.body || []) {
        s += genStatement(inner, ctx, indent + '    ') + '\n';
      }
      s += `${indent}}`;
      return s;
    }
    case 'ExprStmt': {
      const e = genExpr(st.expr, ctx);
      // If expr is void-like (list add/remove returns ()), still `?;` works.
      return `${indent}let _ = (${e});`;
      // Note: `let _ = (vex_list_add(...)?);` — `?` propagates before binding. Good.
      // For func calls `foo()?`, `let _ = (foo()?);` discards value, propagates Err. Good.
    }
    default:
      return `${indent}// unknown stmt ${st.type}`;
  }
}

// Vexel 2.0: `error` is an object { message, type, file, line, column }
// that still prints as its message.
function genTryErrorBinding(indent, file, line, column) {
  return `${indent}let mut __vex_em = std::collections::HashMap::new();\n` +
    `${indent}__vex_em.insert("message".to_string(), VexVal::Str(__vex_e.clone()));\n` +
    // Vexel 3.4 Atlas: typed engine errors carry their kind in the
    // message header — surface it as the error object type so that
    // `error.type` tells the truth (everything else stays RuntimeError).
    `${indent}let mut __vex_etype = String::from("RuntimeError");\n` +
    `${indent}{\n` +
    `${indent}    let __vex_prefix = "Atlas Error\\n\\nType: ";\n` +
    `${indent}    if __vex_e.starts_with(__vex_prefix) {\n` +
    `${indent}        let __vex_rest = &__vex_e[__vex_prefix.len()..];\n` +
    `${indent}        if let Some(__vex_nl) = __vex_rest.find('\\n') {\n` +
    `${indent}            __vex_etype = __vex_rest[..__vex_nl].to_string();\n` +
    `${indent}        }\n` +
    `${indent}    }\n` +
    `${indent}}\n` +
    `${indent}__vex_em.insert("type".to_string(), VexVal::Str(__vex_etype));\n` +
    `${indent}__vex_em.insert("file".to_string(), VexVal::Str("${file}".to_string()));\n` +
    `${indent}__vex_em.insert("line".to_string(), VexVal::Int(${line}));\n` +
    `${indent}__vex_em.insert("column".to_string(), VexVal::Int(${column}));\n` +
    `${indent}let __vex_error = VexVal::Struct(std::rc::Rc::new(std::cell::RefCell::new(VexStruct { type_name: "error".to_string(), fields: __vex_em })));`;
}

function genTry(st, ctx, indent) {
  const inFunc = ctx.inFunction;
  const errFile = rustEscape(path.basename((ctx.currentScope && ctx.currentScope.file) || 'main.vxl'));
  const errLine = (st.token && st.token.line) || 1;
  const errCol = (st.token && st.token.column) || 1;
  if (!inFunc) {
    // Top-level: closure returns Result<(), String>
    let s = '';
    s += `${indent}{\n`;
    s += `${indent}    let __vex_try: Result<(), String> = (|| -> Result<(), String> {\n`;
    const bodyCtx = Object.assign({}, ctx, { inTryClosure: false, inCatch: false });
    for (const inner of st.tryBody) {
      s += genStatement(inner, bodyCtx, indent + '        ') + '\n';
    }
    s += `${indent}        Ok(())\n`;
    s += `${indent}    })();\n`;
    s += `${indent}    if let Err(__vex_e) = __vex_try {\n`;
    s += genTryErrorBinding(indent + '        ', errFile, errLine, errCol) + '\n';
    const catchCtx = Object.assign({}, ctx, { inCatch: true });
    // Silence unused warning if error not used: prefix with underscore? Keep as is; Rust warns but compiles.
    for (const inner of st.catchBody) {
      s += genStatement(inner, catchCtx, indent + '        ') + '\n';
    }
    // Avoid unused variable warning by referencing
    s += `${indent}        let _ = &__vex_error;\n`;
    s += `${indent}    }\n`;
    s += `${indent}}`;
    return s;
  }
  // In function: closure returns Result<Option<VexVal>, String>
  let s = '';
  s += `${indent}{\n`;
  s += `${indent}    let __vex_try: Result<Option<VexVal>, String> = (|| -> Result<Option<VexVal>, String> {\n`;
  const bodyCtx = Object.assign({}, ctx, { inTryClosure: true, inCatch: false });
  for (const inner of st.tryBody) {
    s += genStatement(inner, bodyCtx, indent + '        ') + '\n';
  }
  s += `${indent}        Ok(None)\n`;
  s += `${indent}    })();\n`;
  s += `${indent}    match __vex_try {\n`;
    s += `${indent}        Err(__vex_e) => {\n`;
    s += genTryErrorBinding(indent + '            ', errFile, errLine, errCol) + '\n';
    const catchCtx = Object.assign({}, ctx, { inTryClosure: false, inCatch: true });
  for (const inner of st.catchBody) {
    s += genStatement(inner, catchCtx, indent + '            ') + '\n';
  }
  s += `${indent}            let _ = &__vex_error;\n`;
  s += `${indent}        }\n`;
  s += `${indent}        Ok(Some(__vex_v)) => { return Ok(__vex_v); }\n`;
  s += `${indent}        Ok(None) => {}\n`;
  s += `${indent}    }\n`;
  s += `${indent}}`;
  return s;
}

function genVarAssign(st, ctx, indent) {
  const target = st.target;
  const val = genExpr(st.value, ctx);
  if (target.type === 'VarRef' || target.type === 'OutputRef') {
    const name = target.type === 'OutputRef' ? 'output' : target.name;
    if (name === 'output') {
      return `${indent}vex_set_output((${val}));`;
    }
    if (ctx.inFunction) {
      if (ctx.locals.has(name)) {
        return `${indent}v_${sanitizeIdent(name)} = (${val});`;
      }
      ctx.locals.add(name);
      return `${indent}let mut v_${sanitizeIdent(name)} = (${val});`;
    }
    const key = globalKey(ctx.currentPrefix, name);
    return `${indent}vex_set("${rustEscape(key)}", (${val}));`;
  }
  if (target.type === 'FieldAccess') {
    const res = target._resolved || {};
    if (res.kind === 'module-var') {
      const tprefix = resolveModulePrefix(ctx, res.moduleName);
      const key = globalKey(tprefix, res.name);
      return `${indent}vex_set("${rustEscape(key)}", (${val}));`;
    }
    const base = genExpr(target.object, ctx);
    const field = target.field;
    return `${indent}vex_field_set(&(${base}), "${rustEscape(field)}", (${val}))?;`;
  }
  if (target.type === 'IndexAccess') {
    const base = genExpr(target.object, ctx);
    const idx = genExpr(target.index, ctx);
    return `${indent}vex_index_set(&(${base}), &(${idx}), (${val}))?;`;
  }
  return `${indent}// invalid assign`;
}

function genExpr(node, ctx) {
  if (UI_NODE_TYPES.has(node.type)) {
    throw new Error('INTERNAL: UI syntax reached the console backend (needs a window; use the UI backend).');
  }
  switch (node.type) {
    case 'IntLit':
      return `VexVal::Int(${node.value}i64)`;
    case 'FloatLit':
      return `VexVal::Float((${node.value}) as f64)`;
    case 'StrLit':
      return `VexVal::Str("${rustEscape(node.value)}".to_string())`;
    case 'BoolLit':
      return `VexVal::Bool(${node.value ? 'true' : 'false'})`;
    case 'VarRef': {
      const r = node._resolved || {};
      if (r.kind === 'local') {
        return `v_${sanitizeIdent(node.name)}.clone()`;
      }
      if (r.kind === 'global') {
        const key = globalKey(ctx.currentPrefix, node.name);
        return `vex_get("${rustEscape(key)}")`;
      }
      if (r.kind === 'output') {
        return `vex_get_output()`;
      }
      // Vexel 2.9: program command-line arguments (excluding argv[0]).
      if (r.kind === 'args') {
        return `vex_args()`;
      }
      if (r.kind === 'func-call-zero') {
        const fname = `${ctx.currentPrefix}__${sanitizeIdent(node.name)}`;
        return `${fname}()?`;
      }
      // Fallback (should not happen if semantic passed): try local then global
      if (ctx.inFunction && ctx.locals.has(node.name)) {
        return `v_${sanitizeIdent(node.name)}.clone()`;
      }
      const key = globalKey(ctx.currentPrefix, node.name);
      return `vex_get("${rustEscape(key)}")`;
    }
    case 'OutputRef':
      return `vex_get_output()`;
    case 'ErrorRef':
      return `__vex_error.clone()`;
    case 'BinaryExpr': {
      const L = genExpr(node.left, ctx);
      const R = genExpr(node.right, ctx);
      const op = node.op;
      // Vexel 3.4 Atlas: dedicated matrix multiplication. The runtime
      // validates tensor shapes and reports ShapeError with location.
      if (op === '@' || ((node._resolved || {}).kind === 'tensor-matmul')) {
        return `vex_tensor_matmul(&(${L}), &(${R}))?`;
      }
      const m = {
        '+': 'vex_add',
        '-': 'vex_sub',
        '*': 'vex_mul',
        '/': 'vex_div',
        '%': 'vex_rem',
        '==': 'vex_eq',
        '!=': 'vex_neq',
        '>': 'vex_gt',
        '<': 'vex_lt',
        '>=': 'vex_gte',
        '<=': 'vex_lte',
        'and': 'vex_and',
        'or': 'vex_or',
      }[op];
      if (!m) throw new Error(`Unknown op ${op}`);
      return `${m}(&(${L}), &(${R}))?`;
    }
    case 'UnaryExpr': {
      const E = genExpr(node.expr, ctx);
      if (node.op === 'not') return `vex_not(&(${E}))?`;
      if (node.op === '-') return `vex_neg(&(${E}))?`;
      throw new Error(`Unknown unary ${node.op}`);
    }
    case 'CallExpr': {
      const r = node._resolved || {};
      // Vexel 3.5 Atlas: differentiable activations.
      if (r.kind === 'tensor-activation') {
        return `vex_tensor_${r.name}(&(${genExpr(node.args[0], ctx)}))?`;
      }
      // Vexel 3.4 Atlas: scalar tensor + random tensor constructors.
      if (r.kind === 'tensor-scalar') {
        return `vex_tensor_data(&(${genExpr(node.args[0], ctx)}))?`;
      }
      if (r.kind === 'random-tensor') {
        const shapeNode = node.args[0];
        const shapeExpr = shapeNode.type === 'TensorCons'
          ? genTensorDataList(shapeNode.elements, ctx)
          : genExpr(shapeNode.index, ctx);
        return `vex_tensor_random(&(${shapeExpr}))?`;
      }
      if (r.kind === 'func-call') {
        const fname = `${r.module}__${sanitizeIdent(r.name)}`;
        // r.module is scope.name, not prefix! Need prefix lookup.
        // Scope name is basename; prefix is m<i>_<basename>. Find prefix by scope name?
        // Better: current module's prefix for local calls.
        // For local calls, r.module === currentScope.name, use currentPrefix.
        const prefix = ctx.currentPrefix;
        const args = node.args.map((a) => genExpr(a, ctx)).join(', ');
        return `${prefix}__${sanitizeIdent(r.name)}(${args})?`;
      }
      if (r.kind === 'module-func-call') {
        const tprefix = resolveModulePrefix(ctx, r.moduleName);
        const args = node.args.map((a) => genExpr(a, ctx)).join(', ');
        return `${tprefix}__${sanitizeIdent(r.name)}(${args})?`;
      }
      // Atlas v0.5: model methods — m.forward x (value) and the bare
      // effect calls m.eval / m.train (runtime validates the base).
      if (r.kind === 'model-forward') {
        const base = genExpr(node.callee.object, ctx);
        const arg = genExpr(node.args[0], ctx);
        return `vex_model_forward(&(${base}), &(${arg}))?`;
      }
      if (r.kind === 'model-member-call') {
        const base = genExpr(node.callee.object, ctx);
        return `vex_model_member_get(&(${base}), "${rustEscape(r.member)}")?`;
      }
      if (r.kind === 'list-add') {
        const base = genExpr(node.callee.object, ctx);
        const arg = genExpr(node.args[0], ctx);
        return `({ vex_list_add(&(${base}), &(${arg}))?; VexVal::Null })`;
      }
      if (r.kind === 'list-remove') {
        const base = genExpr(node.callee.object, ctx);
        const arg = genExpr(node.args[0], ctx);
        return `({ vex_list_remove(&(${base}), &(${arg}))?; VexVal::Null })`;
      }
      // Fallback: try to infer
      throw new Error(`Unresolved call`);
    }
    case 'FieldAccess': {
      const r = node._resolved || {};
      // Vexel 3.4 Atlas: tensor members (shape/rank/size/dtype/device/
      // transpose/flatten/reductions).
      if (r.kind === 'tensor-member') {
        const base = genExpr(node.object, ctx);
        return `vex_tensor_get(&(${base}), "${rustEscape(r.member)}")?`;
      }
      // Atlas v0.5: Model members (reads, computed info, eval/train
      // effects). Also the target for members resolved on `any` bases —
      // the runtime falls back to plain field access for non-Models.
      if (r.kind === 'model-member') {
        const base = genExpr(node.object, ctx);
        return `vex_model_member_get(&(${base}), "${rustEscape(r.member)}")?`;
      }
      // Vexel 2.9: enum values are tagged strings at runtime; the static
      // enum type carries the safety.
      if (r.kind === 'enum-lit') {
        return `VexVal::Str("${rustEscape(r.value)}".to_string())`;
      }
      // Vexel 2.9: console task handle facets.
      if (r.kind === 'task-cancel') {
        const base = genExpr(node.object, ctx);
        return `vex_task_cancel(&(${base}))?`;
      }
      if (r.kind === 'task-state') {
        const base = genExpr(node.object, ctx);
        return `vex_task_state(&(${base}))?`;
      }
      if (r.kind === 'task-result') {
        const base = genExpr(node.object, ctx);
        return `vex_task_result(&(${base}))?`;
      }
      if (r.kind === 'task-error') {
        const base = genExpr(node.object, ctx);
        return `vex_task_error(&(${base}))?`;
      }
      if (r.kind === 'module-var') {
        const tprefix = resolveModulePrefix(ctx, r.moduleName);
        const key = globalKey(tprefix, r.name);
        return `vex_get("${rustEscape(key)}")`;
      }
      if (r.kind === 'module-func-zero') {
        const tprefix = resolveModulePrefix(ctx, r.moduleName);
        return `${tprefix}__${sanitizeIdent(r.name)}()?`;
      }
      if (r.kind === 'struct-field' || r.kind === 'any-field') {
        const base = genExpr(node.object, ctx);
        return `vex_field_get(&(${base}), "${rustEscape(node.field)}")?`;
      }
      if (r.kind === 'length-prop') {
        const base = genExpr(node.object, ctx);
        return `vex_len(&(${base}))?`;
      }
      // Fallback
      const base = genExpr(node.object, ctx);
      return `vex_field_get(&(${base}), "${rustEscape(node.field)}")?`;
    }
    case 'IndexAccess': {
      const rx = node._resolved || {};
      // Vexel 3.4 Atlas constructors (tensor/zeros/ones [...]).
      if (rx.kind === 'tensor-data') return `vex_tensor_data(&(${genExpr(node.index, ctx)}))?`;
      if (rx.kind === 'tensor-zeros') return `vex_tensor_zeros(&(${genExpr(node.index, ctx)}))?`;
      if (rx.kind === 'tensor-ones') return `vex_tensor_ones(&(${genExpr(node.index, ctx)}))?`;
      // Vexel 3.4 Atlas: x.reshape [...] (object is the reshape field).
      // A bare IntLit index means a single dimension: x.reshape [4].
      if (rx.kind === 'tensor-reshape') {
        const shapeExpr = node.index.type === 'IntLit'
          ? `VexVal::List(Rc::new(RefCell::new(vec![VexVal::Int(${node.index.value}i64)])))`
          : genExpr(node.index, ctx);
        return `vex_tensor_reshape(&(${genExpr(node.object.object, ctx)}), &(${shapeExpr}))?`;
      }
      // Vexel 3.4 Atlas: tensor element / sub-tensor.
      if (rx.kind === 'tensor-index') {
        const base = genExpr(node.object, ctx);
        const idx = genExpr(node.index, ctx);
        return `vex_tensor_index(&(${base}), &(${idx}))?`;
      }
      const base = genExpr(node.object, ctx);
      const idx = genExpr(node.index, ctx);
      return `vex_index_get(&(${base}), &(${idx}))?`;
    }
    case 'ListLit': {
      const elems = node.elements.map((e) => genExpr(e, ctx)).join(', ');
      return `VexVal::List(Rc::new(RefCell::new(vec![${elems}])))`;
    }
    case 'TensorCons': {
      const rx = node._resolved || {};
      const dataExpr = genTensorDataList(node.elements, ctx);
      if (rx.kind === 'tensor-zeros') return `vex_tensor_zeros(&(${dataExpr}))?`;
      if (rx.kind === 'tensor-ones') return `vex_tensor_ones(&(${dataExpr}))?`;
      return `vex_tensor_data(&(${dataExpr}))?`;
    }
    case 'LengthOf': {
      const e = genExpr(node.expr, ctx);
      return `vex_len(&(${e}))?`;
    }
    case 'NumberOf': {
      const e = genExpr(node.expr, ctx);
      return `vex_number_of(&(${e}))?`;
    }
    case 'CharAt': {
      const b = genExpr(node.base, ctx);
      const idx = genExpr(node.index, ctx);
      return `vex_char_at(&(${b}), &(${idx}))?`;
    }
    case 'RandomExpr': {
      const lo = genExpr(node.low, ctx);
      const hi = genExpr(node.high, ctx);
      return `vex_rand(&(${lo}), &(${hi}))?`;
    }
    case 'GpuInfo': {
      // Vexel 3.6 Atlas: never raises — a missing backend reads as false/0/"".
      if (node.info === 'available') return `VexVal::Bool(vgpu_available())`;
      if (node.info === 'count') return `VexVal::Int(vgpu_count() as i64)`;
      return `VexVal::Str(vgpu_name())`;
    }
    case 'StructInst': {
      const parts = node.fields.map((f) => `("${rustEscape(f.name)}".to_string(), (${genExpr(f.value, ctx)}))`).join(', ');
      return `vex_struct_new("${rustEscape(node.structName)}", vec![${parts}])`;
    }
    case 'NullLit': {
      return 'VexVal::Null';
    }
    case 'ObjectLit': {
      // Vexel 2.0 anonymous object — a struct with no type name.
      const parts = node.fields.map((f) => `("${rustEscape(f.name)}".to_string(), (${genExpr(f.value, ctx)}))`).join(', ');
      return `vex_struct_new("", vec![${parts}])`;
    }
    case 'JsonRead': {
      const p = genExpr(node.path, ctx);
      return `vex_json_read(&(((${p})).to_display()))?`;
    }
    case 'LoadModelExpr': {
      // Atlas v0.5: m = load model "<dir>".
      const p = genExpr(node.path, ctx);
      return `vex_model_load(&(((${p})).to_display()))?`;
    }
    case 'CreateModelExpr': {
      // Atlas v0.5: m = create model <config>.
      const c = genExpr(node.config, ctx);
      return `vex_model_create(&(${c}))?`;
    }
    case 'ModelInfoExpr': {
      // Atlas v0.5: info = model info "<dir>" (config-only inspection).
      const p = genExpr(node.path, ctx);
      return `vex_model_info(&(((${p})).to_display()))?`;
    }
    case 'HttpGet': {
      // Vexel 2.9: console programs fetch over plain TCP (http://).
      const u = genExpr(node.url, ctx);
      return `vex_http_request("GET", &(${u}), &VexVal::Null, &VexVal::Null)?`;
    }
    case 'RunExpr': {
      const c = genExpr(node.cmd, ctx);
      return `vex_term_run_capture(&(${c}))?`;
    }
    case 'HttpRequest': {
      // Vexel 2.9: http <method> url [, body] [, headers].
      const u = genExpr(node.url, ctx);
      const b = node.body ? genExpr(node.body, ctx) : 'VexVal::Null';
      const h = node.headers ? genExpr(node.headers, ctx) : 'VexVal::Null';
      return `vex_http_request("${node.method}", &(${u}), &(${b}), &(${h}))?`;
    }
    case 'FileRead': {
      const p = genExpr(node.path, ctx);
      return `vex_file_read(&(((${p})).to_display()))?`;
    }
    case 'FileExists': {
      const p = genExpr(node.path, ctx);
      return `vex_file_exists(&(((${p})).to_display()))`;
    }
    case 'DirExists': {
      const p = genExpr(node.path, ctx);
      return `vex_dir_exists(&(((${p})).to_display()))`;
    }
    case 'FileSize': {
      const p = genExpr(node.path, ctx);
      return `vex_file_size(&(((${p})).to_display()))?`;
    }
    case 'DirList': {
      const p = genExpr(node.path, ctx);
      return `vex_dir_list(&(((${p})).to_display()))?`;
    }
    default:
      throw new Error(`Unknown expr ${node.type}`);
  }
}

// Vexel 2.9: test-mode compilation. Module inits run first (tests may
// use any global), then each collected test runs with per-test catching.
// Tests share module globals; a failing test never stops the suite.
function collectTests(stmts, into) {
  for (const st of stmts || []) {
    if (!st || typeof st !== 'object') continue;
    if (st.type === 'TestBlock') { into.push(st); continue; }
    if (st.type === 'IfStmt') {
      for (const br of st.branches || []) collectTests(br.body, into);
      collectTests(st.elseBody, into);
    } else if (st.type === 'TryStmt') {
      collectTests(st.tryBody, into);
      collectTests(st.catchBody, into);
    } else if (st.type === 'RepeatCount' || st.type === 'RepeatTill') {
      collectTests(st.body, into);
    } else if (st.type === 'MatchStmt') {
      for (const arm of st.arms || []) collectTests(arm.body, into);
    }
  }
}

function genTestFn(prefix, idx, tb, scope, prefixMap, scopes, modules) {
  const lines = [];
  lines.push(`fn ${prefix}__test${idx}() -> Result<(), String> {`);
  const ctx = {
    prefixMap,
    currentPrefix: prefix,
    currentScope: scope,
    scopes,
    modules,
    inFunction: false,
    locals: new Set(),
    inTryClosure: false,
    inCatch: false,
    indent: '    ',
  };
  for (const st of tb.body) {
    lines.push(genStatement(st, ctx, '    '));
  }
  lines.push('    Ok(())');
  lines.push('}');
  return lines.join('\n');
}

function generateTest(loadResult, analyzeResult) {
  const { modules, order } = loadResult;
  const { scopes } = analyzeResult;
  const runtime = loadRuntime();
  const prefixMap = buildPrefixes(order);
  const norm = (p) => path.normalize(p);
  const prefixOf = (absPath) => prefixMap.get(norm(absPath));

  const out = [];
  out.push('// Generated by Vexel 2.9 compiler (test mode). Do not edit.');
  out.push(runtime);
  out.push('');

  for (const absPath of order) {
    const prefix = prefixOf(absPath);
    const scope = scopes.get(norm(absPath));
    out.push(`// ===== Module ${modules.get(norm(absPath)).file} (${prefix}) =====`);
    for (const [, fn] of scope.functions) {
      out.push(genFunction(prefix, fn, scope, scopes, prefixMap, modules));
      out.push('');
    }
  }

  // Emit test functions (source order across modules).
  const tests = [];
  for (const absPath of order) {
    const prefix = prefixOf(absPath);
    const scope = scopes.get(norm(absPath));
    const mod = modules.get(norm(absPath));
    const found = [];
    collectTests(mod.ast.body, found);
    for (const tb of found) {
      tests.push({ tb, idx: tests.length, prefix, scope });
    }
  }
  for (const t of tests) {
    out.push(genTestFn(t.prefix, t.idx, t.tb, t.scope, prefixMap, scopes, modules));
    out.push('');
  }

  // Inits (same as normal mode, minus declarations).
  for (const absPath of order) {
    const prefix = prefixOf(absPath);
    const scope = scopes.get(norm(absPath));
    const mod = modules.get(norm(absPath));
    const guard = `${prefix.toUpperCase()}__INIT`;
    out.push(`static ${guard}: AtomicBool = AtomicBool::new(false);`);
    out.push(`fn ${prefix}__init() -> Result<(), String> {`);
    out.push(`    if ${guard}.swap(true, Ordering::SeqCst) { return Ok(()); }`);
    const ctx = {
      prefixMap,
      currentPrefix: prefix,
      currentScope: scope,
      scopes,
      modules,
      inFunction: false,
      locals: new Set(),
      inTryClosure: false,
      inCatch: false,
      indent: '    ',
    };
    for (const st of mod.ast.body) {
      if (st.type === 'ImportDecl' || st.type === 'StructDecl' || st.type === 'EnumDecl' || st.type === 'TestBlock' || st.type === 'FuncDecl' || st.type === 'ComponentDecl' || st.type === 'ThemeDecl' || st.type === 'StyleDecl') continue;
      if (st.type === 'PublicDecl') {
        const inner = st.decl;
        if (!inner) continue;
        if (inner.type === 'FuncDecl' || inner.type === 'StructDecl' || inner.type === 'EnumDecl') continue;
        out.push(genStatement(inner, ctx, '    '));
        continue;
      }
      out.push(genStatement(st, ctx, '    '));
    }
    out.push('    Ok(())');
    out.push('}');
    out.push('');
  }

  out.push('fn vex_main() -> Result<(), String> {');
  for (const absPath of order) {
    const prefix = prefixOf(absPath);
    out.push(`    ${prefix}__init()?;`);
  }
  out.push('    println!("Vexel Test Runner");');
  if (tests.length === 0) {
    out.push('    println!("No tests found.");');
  }
  out.push('    let mut __vex_passed: i64 = 0;');
  out.push('    let mut __vex_failed: i64 = 0;');
  for (const t of tests) {
    const label = rustEscape(t.tb.name);
    out.push(`    match ${t.prefix}__test${t.idx}() {`);
    out.push(`        Ok(()) => { __vex_passed += 1; println!("\\u{2713} ${label}"); },`);
    out.push(`        Err(__vex_e) => { __vex_failed += 1; println!("\\u{2717} ${label} — {}", __vex_e); },`);
    out.push('    };');
  }
  out.push('    println!("");');
  out.push('    println!("{} passed", __vex_passed);');
  out.push('    println!("{} failed", __vex_failed);');
  out.push('    if __vex_failed > 0 { return Err(format!("{} test(s) failed", __vex_failed)); }');
  out.push('    Ok(())');
  out.push('}');
  out.push('');
  out.push('fn main() {');
  out.push('    if let Err(e) = vex_main() {');
  out.push('        eprintln!("{}", e);');
  out.push('        std::process::exit(1);');
  out.push('    }');
  out.push('}');
  out.push('');

  return out.join('\n');
}

module.exports = { generate, generateTest };
